# Generated by Django 3.1 on 2022-08-29 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20220829_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('category', models.CharField(blank=True, choices=[('Business', 'Business'), ('Politics', 'Politics'), ('Corporate', 'Corporate'), ('Health', 'Health'), ('Education', 'Education'), ('Science', 'Science'), ('Foods', 'Foods'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Corporate', 'Corporate')], default='Business', max_length=50, null=True)),
                ('heading', models.CharField(max_length=255)),
                ('news_cover', models.FileField(upload_to='media/')),
                ('news', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
