# Generated by Django 3.1 on 2022-08-31 12:05

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Email',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Politics', 'Politics'), ('Corporate', 'Corporate'), ('Health', 'Health'), ('Education', 'Education'), ('Science', 'Science'), ('Foods', 'Foods'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Corporate', 'Corporate'), ('sports', 'sports')], default='Business', max_length=50, null=True),
        ),
    ]
