# Generated by Django 3.1 on 2022-09-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
