# Generated by Django 3.1 on 2022-09-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
